FROM postgres:16-alpine

ENV POSTGRES_DB=home_library
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=rub54321
ENV PGDATA=/var/lib/postgresql/data/pgdata

RUN apk add --no-cache \
    curl \
    postgresql-contrib

RUN mkdir -p /docker-entrypoint-initdb.d
RUN mkdir -p /etc/postgresql

COPY database/init/*.sql /docker-entrypoint-initdb.d/


RUN chown -R postgres:postgres /docker-entrypoint-initdb.d

EXPOSE 5432

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD pg_isready -U $POSTGRES_USER -d $POSTGRES_DB || exit 1

CMD ["postgres"]
